apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 054037113048.dkr.ecr.ap-northeast-2.amazonaws.com/joing-recai-repo
    newTag: v0.1.76
  - name: 054037113048.dkr.ecr.ap-northeast-2.amazonaws.com/joing-genai-repo
    newTag: v0.0.4
